//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Utility;
using System.Collections.Generic;
namespace Game.Entity.Behavior
{
	public class GBehavior : MonoBehaviour,IEntityComponent
	{
		public bool isAlive =true;
		public bool IsAlive { get { return this.isAlive; } }
	

		
		public List<GBehavior> others = new List<GBehavior>();
		
		public virtual bool TestIsAlive (GEntity entity, GRoom room)
		{
			return true;
		}
		
		public virtual void Init(GEntity entity){
		}
		public void KUpdate(GEntity entity, GRoom room){
			isAlive = TestIsAlive (entity, room);
			if (!isAlive) return;
			
			for(int i = 0 ; i < others.Count;i++){
				others[i].KUpdate(entity,room);
			}
			Do (entity, room);
		}
		public virtual void Do(GEntity entity, GRoom room){
		}
	}
}

