//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Utility;
using System.Collections.Generic;
namespace Game.Entity.Behavior
{
	public class GBehavior : MonoBehaviour
	{
		public bool isAlive =true;


		public List<GBehavior> otherBhr = new List<GBehavior>();

		public void KUpdate(GEntity entity, GRoom room){
			for(int i = 0 ; i < otherBhr.Count;i++){
				otherBhr[i].KUpdate(entity,room);
			}
			Do (entity, room);
		}
		public virtual void Do(GEntity entity, GRoom room){
		}
	}
}

