//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace Game.Entity.Behavior
{
	public class GBhvApplyForcePlayerVelocity : GBehavior
	{
		public float force;
		public override void Init (GEntity entity)
		{
			//Debug.Log ("INIT CALLED");
			base.Init (entity);
		}
		public override void Do (GEntity entity, GRoom room)
		{
			base.Do (entity, room);
			if (GPlayer.PlayerEntity == null) return;
			//Debug.Log (entity.gameObject.name + " " + entity.tag + " " +force);
			var dir = GPlayer.PlayerEntity.moveAmountOld.normalized;//.normalized;
			//Debug.Log ("Do CALLED" +GPlayer.PlayerEntity.moveAmountOld + dir);
			//entity.Move (new Vector3 (dir.x, 0, dir.z).normalized * force);
			entity.AddForce(dir*force * (1.0f/Time.fixedDeltaTime));
		}
	}
}

