//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Game.Entity.Behavior 
{
	public class GBhvLookAtFiringDirection :GBehavior
	{
		public override void Init (GEntity entity)
		{
			entity.E_Attack += Hdr_Attack;
		}
		void Hdr_Attack(GEntity entity, int direction){
			entity.rotation = GInfo.dirLook[direction];
		}
	}
}

