//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace Game.Entity.Behavior
{
	public class GBhvApplyForce : GBehavior
	{
		public GameObject positionFrom;
		public float force;
		public override void Do (GEntity entity, GRoom room)
		{
			base.Do (entity, room);
			var dir = (entity.transform.position - positionFrom.transform.position);
			entity.body.AddForce(new Vector3 (dir.x, 0, dir.z).normalized*force);
		}
	}
}

