//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Utility;
namespace Game.Entity.Behavior
{
	public class GBhvTimer : GBehavior
	{
		public float timeInit,timeMax;
		EasyTimer timer;
		override public void Start(){
			base.Start ();
			timer = new EasyTimer (timeInit, timeMax);
		}
		override public void KUpdate(GEntity entity, GRoom room){
			if (!timer.Tick (UnityEngine.Time.deltaTime))
				return;
			base.KUpdate (entity, room);

		}
	}
}

