//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NS_Behaviour.NCondition
{
	public class Condition
	{
		public Condition (Entity entity)
		{
		}
		public virtual int Process(Entity entity, Room room,int bhvProcessResult){
			return bhvProcessResult;
		}
	}
}

