//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Utility;
using System.Collections.Generic;
namespace Game.Entity
{
	public interface IEntityComponent
	{

		bool IsAlive{ get;}

		bool TestIsAlive (GEntity entity, GRoom room);
		void Init (GEntity entity);
		void KUpdate (GEntity entity, GRoom room);
		void Do (GEntity entity, GRoom room);
	}
}

