//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace NWeapon
{
	public class GunBasic : Weapon
	{
		
		public GunBasic (){
			this.typeBullet = BulletManager.KTypes.Normal;
		}
		public override void Attack (Entity entity,Room room,UnityEngine.Vector3 direction)
		{
			base.Attack (entity,room, direction);
			var bullet = BulletManager.E_RequestBullet (BulletManager.KTypes.Normal);
			bullet.SetVelocity (direction * speed	);
			bullet.targets = this.targets;
			bullet.hpChange = -1;
			bullet.forceApplied = 3;
			room.AddEntity (bullet, entity.transform.localPosition.x, entity	.transform.localPosition.y, false);
		}
	}
}

