//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace NWeapon
{
	public class Weapon
	{
		internal BulletManager.KTypes typeBullet;
		internal float backSwing = 5.0f, speed = 10.0f;
		internal List<Entity.KType> targets;


		public Weapon ()
		{
			targets = new List<Entity.KType> ();
		}
		public Weapon SetTargets(params Entity.KType[] targetList){
			foreach (var t in targetList) {
				targets.Add(t);
			}
			return this;
		}
		public Weapon SetSpeed(float s){
			this.speed = s;
			return this;
		}
		public virtual void Attack(Entity entity,Room room, Vector3 direction){
			try{
				((EntityMove)entity).AddForceVelocity(-direction * backSwing);
			}
			catch{
			}
			//return null;
			
		}
	}
}

