//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace NWeapon
{
	public class Weapon
	{
		internal List<Entity.KType> targets;

		public Weapon ()
		{
			targets = new List<Entity.KType> ();
		}
		public Weapon SetTargets(params Entity.KType[] targetList){
			foreach (var t in targetList) {
				targets.Add(t);
			}
			return this;
		}
		public virtual void Attack(Entity entity,Room room, Vector3 direction){
			//return null;
			
		}
	}
}

