//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utility
{
	public class EasyTimer
	{
		float time,timeMax;
		public EasyTimer (float timeInit, float timeMax)
		{
			this.time = timeInit;
			this.timeMax = timeMax;
		}
		public bool IsDone(){
			return time > timeMax;
		}
		public void ReadyNextTick(){
			time = 9999999;
		}
		public bool Tick(float timeElapsed){
			time += timeElapsed;
			bool done = time > timeMax;
			if (done) {
				time = 0;
				return true;
			}
			return false;
		}
	}
}

