//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Game
{
	public class GameTags
	{
		public static string World = "TWorld", Player = "TPlayer", Enemy = "TEnemy";
		public GameTags ()
		{
		}
	}
}

