//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace Game
{
	public class GInfo
	{
		public static Vector3[] dirLook = new Vector3[]{
			new Vector3 (0, 180, 0),new Vector3 (0, 270, 0),new Vector3(), new Vector3(0,90,0)
		};
	}
}

