//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Game.Entity;
namespace Game
{
	public class GPlayer : MonoBehaviour
	{
		public static GEntity Entity;
		public GEntity myEntitiy;
		public PlayerController playerController;
		public GEntity myBullet;

		void Start(){
			GPlayer.Entity = myEntitiy;
			playerController.myEntity = myEntitiy;
			myEntitiy.E_Attack = Attack;

		}
		public void KUpdate(GRoom room){
			
			myEntitiy.KUpdate (room);
			playerController.KUpdate ();

		}
		public void Attack(Vector3 direction){
			
		}

		public void EnterRoom (GRoom room)
		{
			room.AddPlayer (myEntitiy,-1);
		}
	}
}

