//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using Game.Entity;
using Game.Entity.Behavior;
namespace Game
{
	public class GPlayer : MonoBehaviour
	{
		public static GEntity PlayerEntity;
		public static Vector3 PlayerPosition;

		public GEntity P_PlayerBase;
		public GBehavior behaviorPlayer;
		public PlayerController playerController;

		public GEntity myEntitiy;

		void Awake(){
			myEntitiy = GetNewPlayer ();
			playerController.myEntity = myEntitiy;

		}
		public GEntity GetNewPlayer(){
			var player = Instantiate (P_PlayerBase);
			player.AddBehavior (Instantiate(behaviorPlayer));
			return player;
		}

		public void KFixedUpdate (GRoom roomActive)
		{
			myEntitiy.KFixedUpdate (roomActive);
			playerController.KFixedUpdate ();
		}

		public void KUpdate(GRoom room){
			if (myEntitiy == null) return;
			myEntitiy.KUpdate (room);
			GPlayer.PlayerPosition = myEntitiy.position;

			playerController.KUpdate ();

		}

		public void EnterRoom (GRoom room)
		{
			room.AddPlayer (myEntitiy,-1);
		}
	}
}

