//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Game.Entity;
using System.Collections.Generic;
namespace Game
{
	public class GTheme : UnityEngine.MonoBehaviour
	{
		[System.Serializable]
		public class GThemeRoom{
			public GEntity 
				Floor,
				Wall_Boundry;
			public GEntItem Door;
		}
		[System.Serializable]
		public class GThemeEntities{
			public List<GEntity> Simple;
		}

		public GThemeRoom Room;
		public GThemeEntities Entities;



	}
}

