//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NS_Behaviour
{
	public class BhvRunInCircle : Behaviour
	{
		float 
			circelsPerSecond,
			velo,
			angle = 0;
		public BhvRunInCircle (Entity entity,float radius, float circelsPerSecond)
		{
			this.circelsPerSecond = circelsPerSecond;
			velo = (2.0f * 3.14f * radius)*circelsPerSecond;

		}
		public override int Process (Entity entity, Room room)
		{
			//UnityEngine.Debug.Log ("PROCESS RUN IN CIRCLE");
			var entityMove = (EntityMove)entity;
			angle += 6.28f *circelsPerSecond * UnityEngine.Time.deltaTime;
			entityMove.SetVelocity (
				new UnityEngine.Vector3(
				UnityEngine.Mathf.Cos(angle),
				UnityEngine.Mathf.Sin(angle),0) * velo);
			return 0;
		}

	}
}

