//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Data
{
	public class DDoor
	{
		public enum Types{
			Normal,Treausre,Boss,Secret
		}
		public Types type;


		//public bool isLocked = false;
		public DDoor ()
		{
		}
	}
}

