//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NItem
{
	public class Item
	{
		public enum KType {Nothing, Bomb,Money, Weapon};
		public KType meType;
		public int Count = 1;
		
		public Item ()
		{
		}
		
		public Item (KType type, int count)
		{
			this.meType = type;
			this.Count = count;
		}
		public static Item GetMoney(){
			return new Item(KType.Money,1);
		}
		public static Item GetBomb(){
			return new Item(KType.Bomb,1);
		}

	}
}

